
---
 - hosts: headnode
   tasks:

   - name: install EPEL repo
     yum: name=epel-release state=present

   - name: install java and other deps (starting from CentOS minimal!)
     yum: name={{ item }} state=latest
     with_items:
       - "java-{{ java_version }}-openjdk-devel"
       - "maven"
       - "mariadb-server"
       - "wget"
       - "MySQL-python"

   - name: get rabbitmq rpm key
     rpm_key: key=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc state=present

   - name: get erlang from rabbitmq
     yum: name=https://www.rabbitmq.com/releases/erlang/erlang-{{ rabbitmq_erlang_version }}.el7.centos.x86_64.rpm state=present
   
   - name: install rabbitmq via rpm
     yum: name=https://www.rabbitmq.com/releases/rabbitmq-server/v{{ rabbitmq_version }}/rabbitmq-server-{{ rabbitmq_version }}-1.noarch.rpm state=present


   vars:
     java_version: 1.8.0
     rabbitmq_version: 3.6.2
     rabbitmq_erlang_version: 18.3-1
#     rabbitmq_tar: "rabbitmq-server-generic-unix-{{ rabbitmq_version }}.tar.gz"
