
---
 - hosts: headnode
   tasks:

   - name: install EPEL repo
     yum: name=epel-release state=present

   - name: install java and other deps (starting from CentOS minimal!)
     yum: name={{ item }} state=latest
     with_items:
       - "java-{{ java_version }}-openjdk-devel"
       - "erlang"
       - "maven"
       - "mariadb-server"
       - "wget"
       - "MySQL-python"
   
   - name: get rabbitmq rpm key
     rpm_key: key=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc state=present

   - name: install rabbitmq via rpm
     yum: name=https://www.rabbitmq.com/releases/rabbitmq-server/v{{ rabbit_mq_version }}/rabbitmq-server-{{ rabbit_mq_version }}-1.noarch.rpm state=present


   vars:
     java_version: 1.8.0
     rabbit_mq_version: 3.4.1
     rabbit_mq_tar: "rabbitmq-server-generic-unix-{{ rabbit_mq_version }}.tar.gz"
